### ISSUE TITLE
Вопрос по ДЗ-2

### ISSUE THREAD

**Issue by mcarov** [mcarov/servlet-test#1]
@coursar
Допустимо ли в базе хранить только ссылки на изображения, расположенные на сторонних ресурсах, и во время запуска сервлета подгружать их по этим ссылкам?

**Comment by coursar** [comment]
Допустимо, только тогда не нужно их подгружать, пусть там и лежат на сторонних ресурсах. Вам достаточно URL встраивать в `<img src=...>`  браузер их сам загрузит (если они доступны по http/https)
