### ISSUE TITLE
Для этого надо использовать stream'ы, forEach - плохая идея

### ISSUE THREAD

**Issue by coursar** [mcarov/servlet-test#16]
https://github.com/mcarov/servlet-test/blob/df17657b59a463020002f98ddcc89fd0920920ee/src/main/java/ru/itpark/service/CarService.java#L54-L55

**Comment by mcarov** [comment]
Почему?

**Comment by mcarov** [comment]
`Map<Integer, Car> map = getAll().stream().collect(Collectors.toMap(c -> c.getId(), c -> c));
        map.putAll(newList.stream().collect(Collectors.toMap(c -> c.getId(), c -> c)));`

Должно быть что-то вроде этого?
