### ISSUE TITLE
При переходе на Java 11 Findbugs обнаруживает баги, которых не было при работе с Java 8

### ISSUE THREAD

**Issue by mcarov** [mcarov/servlet-test#31]
"C:\Program Files\Java\jdk-11.0.2\bin\java.exe" "-Dmaven.multiModuleProjectDirectory=C:\JavaDev\IdeaProjects\02. Servlet Test" "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\plugins\maven\lib\maven3\bin\m2.conf" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\lib\idea_rt.jar=53266:C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar" org.codehaus.classworlds.Launcher -Didea.version2019.1.1 verify
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building servlet-test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ servlet-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\JavaDev\IdeaProjects\02. Servlet Test\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ servlet-test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to C:\JavaDev\IdeaProjects\02. Servlet Test\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ servlet-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\JavaDev\IdeaProjects\02. Servlet Test\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ servlet-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ servlet-test ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ servlet-test ---
[INFO] Packaging webapp
[INFO] Assembling webapp [servlet-test] in [C:\JavaDev\IdeaProjects\02. Servlet Test\target\servlet-test-1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\JavaDev\IdeaProjects\02. Servlet Test\src\main\webapp]
[INFO] Webapp assembled in [64 msecs]
[INFO] Building war: C:\JavaDev\IdeaProjects\02. Servlet Test\target\servlet-test-1.0-SNAPSHOT.war
[INFO] WEB-INF\web.xml already added, skipping
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy (default) @ servlet-test ---
[INFO] Configured Artifact: com.github.jsimone:webapp-runner:9.0.19.0:jar
[INFO] Configured Artifact: org.apache.tomcat:tomcat-dbcp:9.0.19:jar
[INFO] Copying webapp-runner-9.0.19.0.jar to C:\JavaDev\IdeaProjects\02. Servlet Test\target\dependency\webapp-runner.jar
[INFO] Copying tomcat-dbcp-9.0.19.jar to C:\JavaDev\IdeaProjects\02. Servlet Test\target\dependency\tomcat-dbcp.jar
[INFO] 
[INFO] >>> maven-pmd-plugin:3.11.0:check (default) > :pmd @ servlet-test >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.11.0:pmd (pmd) @ servlet-test ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.11.0:check (default) < :pmd @ servlet-test <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.11.0:check (default) @ servlet-test ---
[INFO] 
[INFO] 
[INFO] >>> findbugs-maven-plugin:3.0.5:check (default) > :findbugs @ servlet-test >>>
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.5:findbugs (findbugs) @ servlet-test ---
[INFO] Fork Value is true
     [java] WARNING: An illegal reflective access operation has occurred
     [java] WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/C:/Users/Dmitry/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
     [java] WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
     [java] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
     [java] WARNING: All illegal access operations will be denied in a future release
     [java] The following classes needed for analysis were missing:
     [java]   java.lang.Object
     [java]   java.io.Serializable
     [java]   java.util.Map
     [java]   javax.naming.InitialContext
     [java]   javax.naming.NamingException
     [java]   java.lang.Exception
     [java]   java.lang.String
     [java]   java.lang.StringBuilder
     [java]   java.sql.PreparedStatement
     [java]   javax.sql.DataSource
     [java]   java.sql.Connection
     [java]   java.sql.Statement
     [java]   java.lang.Throwable
     [java]   java.sql.ResultSet
     [java]   java.util.ArrayList
     [java]   java.util.List
     [java]   java.util.stream.Stream
     [java]   java.util.stream.Collectors
     [java]   java.util.Collection
     [java]   java.util.Iterator
     [java]   java.lang.Integer
     [java]   java.sql.ParameterMetaData
     [java]   java.lang.Long
     [java]   java.io.IOException
     [java]   java.lang.System
     [java]   java.nio.file.Paths
     [java]   java.nio.file.Files
     [java]   java.nio.file.Path
     [java]   java.io.File
     [java]   javax.imageio.ImageIO
     [java]   java.util.UUID
     [java]   java.io.Reader
     [java]   java.io.Writer
     [java]   java.io.PrintStream
     [java]   java.lang.NoSuchFieldError
     [java]   java.lang.NoClassDefFoundError
     [java]   java.awt.image.BufferedImage
     [java]   java.nio.file.attribute.FileAttribute
     [java]   java.lang.UnsatisfiedLinkError
     [java]   java.lang.Error
     [java]   java.lang.IllegalAccessError
     [java]   java.lang.AbstractMethodError
     [java]   java.sql.SQLException
     [java]   java.lang.invoke.LambdaMetafactory
     [java]   java.lang.invoke.MethodHandles$Lookup
     [java]   java.lang.invoke.MethodHandles
     [java]   java.nio.file.OpenOption
     [java]   java.lang.IncompatibleClassChangeError
     [java]   java.lang.RuntimeException
     [java]   java.lang.NoSuchMethodError
     [java]   java.lang.NullPointerException
     [java]   java.lang.ArrayIndexOutOfBoundsException
     [java]   java.lang.ClassFormatError
     [java]   java.lang.VerifyError
     [java]   java.lang.ExceptionInInitializerError
     [java]   java.lang.ClassCastException
     [java] Warnings generated: 23
     [java] Missing classes: 41
[INFO] Done FindBugs Analysis....
[INFO] 
[INFO] <<< findbugs-maven-plugin:3.0.5:check (default) < :findbugs @ servlet-test <<<
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.5:check (default) @ servlet-test ---
[INFO] BugInstance size is 23
[INFO] Error size is 0
[INFO] Total bugs: 23
[INFO] Nullcheck of conn at line 20 of value previously dereferenced in new ru.itpark.service.CarService() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 20]Redundant null check at CarService.java:[line 30] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 22 of value previously dereferenced in new ru.itpark.service.CarService() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 22]Redundant null check at CarService.java:[line 30] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 88 of value previously dereferenced in ru.itpark.service.CarService.create(String, String, String, String, String, String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 88]Redundant null check at CarService.java:[line 92] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 91 of value previously dereferenced in ru.itpark.service.CarService.create(String, String, String, String, String, String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 91]Redundant null check at CarService.java:[line 92] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 134 of value previously dereferenced in ru.itpark.service.CarService.deleteAll() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 134]Redundant null check at CarService.java:[line 137] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 136 of value previously dereferenced in ru.itpark.service.CarService.deleteAll() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 136]Redundant null check at CarService.java:[line 137] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 142 of value previously dereferenced in ru.itpark.service.CarService.deleteById(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 142]Redundant null check at CarService.java:[line 146] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 144 of value previously dereferenced in ru.itpark.service.CarService.deleteById(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 144]Redundant null check at CarService.java:[line 146] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 98 of value previously dereferenced in ru.itpark.service.CarService.getAll() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 98]Redundant null check at CarService.java:[line 104] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of resultSet at line 101 of value previously dereferenced in ru.itpark.service.CarService.getAll() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 101]Redundant null check at CarService.java:[line 104] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 99 of value previously dereferenced in ru.itpark.service.CarService.getAll() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 99]Redundant null check at CarService.java:[line 104] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 111 of value previously dereferenced in ru.itpark.service.CarService.getById(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 111]Redundant null check at CarService.java:[line 118] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of resultSet at line 116 of value previously dereferenced in ru.itpark.service.CarService.getById(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 116]Redundant null check at CarService.java:[line 117] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 114 of value previously dereferenced in ru.itpark.service.CarService.getById(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 114]Redundant null check at CarService.java:[line 118] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 35 of value previously dereferenced in ru.itpark.service.CarService.getLastInsertId() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 35]Redundant null check at CarService.java:[line 39] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of resultSet at line 37 of value previously dereferenced in ru.itpark.service.CarService.getLastInsertId() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 37]Redundant null check at CarService.java:[line 39] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 36 of value previously dereferenced in ru.itpark.service.CarService.getLastInsertId() [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 36]Redundant null check at CarService.java:[line 39] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 45 of value previously dereferenced in ru.itpark.service.CarService.search(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 45]Redundant null check at CarService.java:[line 53] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of resultSet at line 48 of value previously dereferenced in ru.itpark.service.CarService.search(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 48]Redundant null check at CarService.java:[line 53] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 46 of value previously dereferenced in ru.itpark.service.CarService.search(String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 46]Redundant null check at CarService.java:[line 53] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 125 of value previously dereferenced in ru.itpark.service.CarService.updateById(String, String, String, String, String, String, String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 125]Redundant null check at CarService.java:[line 129] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of statement at line 128 of value previously dereferenced in ru.itpark.service.CarService.updateById(String, String, String, String, String, String, String) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 128]Redundant null check at CarService.java:[line 129] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] Nullcheck of conn at line 63 of value previously dereferenced in ru.itpark.service.CarService.updateFromList(List) [ru.itpark.service.CarService, ru.itpark.service.CarService] At CarService.java:[line 63]Redundant null check at CarService.java:[line 82] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
[INFO] 

To see bug detail using the Findbugs GUI, use the following command "mvn findbugs:gui"

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.911 s
[INFO] Finished at: 2019-05-04T17:38:59+03:00
[INFO] Final Memory: 38M/134M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.5:check (default) on project servlet-test: failed with 23 bugs and 0 errors -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

**Comment by coursar** [comment]
https://github.com/spotbugs/spotbugs/issues/756
